import os
import glob
import csv
import cv2


def get_framecount(filename):
    cap = cv2.VideoCapture(filename)
    return int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

def checkrow(row, index):
    if len(row) != 23:
        print(f"Error row {index} is not the proper number of columns: \n{row}\n")
        raise Exception()

def makerow(filename: str):
    row = []
    # Fallout videos
    if "Motorcycle/Fallout/Human/" in filename:
        row.append("Motorcycling")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("What")
        row.append("Motorcycle")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
        row.append("On")
        row.append("Gravel")
    elif "Motorcycle/Fallout/Animal/" in filename:
        label_parts = os.path.basename(filename).lower().split('-')
        row.append("Motorcycling")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        if label_parts[4] == "b":
            row.append("back")
        elif label_parts[4] == "l" or label_parts[4] == "r":
            row.append("side")
        elif label_parts[4] == "f":
            row.append("front")
        row.append("Location")
        row.append("outdoors")
        row.append("What")
        row.append("Motorcycle")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
        row.append("On")
        row.append("Pavement")
        row.append("Agent")
        if label_parts[1] == "b":
            row.append("Bear")
        elif label_parts[1] == "g":
            row.append("Gorilla")
        else:
            row.append("Other")
    elif "Jumping/Fallout/" in filename:
        row.append("Jumping")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        if os.path.basename(filename)[-5] == 'f':
            row.append("Grass")
        elif os.path.basename(filename)[-5] == "r":
            row.append("Gravel")
        else:
            row.append("Pavement")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Running/Fallout/" in filename:
        row.append("Running")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("back")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Gravel")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Standing/Fallout/standing_forest/" in filename:
        row.append("Standing")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("back")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Grass")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Standing/Fallout/standing_town/" in filename:
        row.append("Standing")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("back")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Pavement")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Walking/Fallout/" in filename:
        row.append("Walking")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Gravel")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Sleeping/Fallout/" in filename:
        row.append("Sleeping")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        if "/side-view/" in filename:
            row.append("side")
        else:
            row.append("top")
        row.append("Location")
        row.append("indoors")
        row.append("With")
        row.append("Bed")
        row.append("On")
        if "v" in filename:
            row.append("WoodFloor")
        else:
            row.append("Pavement")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Not Determinable")
        row.append("Weather")
        row.append("Not Determinable")
    elif "ThrowingGrenade/Fallout/" in filename:
        row.append("ThrowingGrenade")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        if "_inside/" in filename:
            row.append("indoors")
        else:
            row.append("outdoors")
        row.append("What")
        row.append("Grenade")
        row.append("On")
        if "_inside/" in filename:
            row.append("NonWoodFloor(inside)")
        else:
            row.append("Gravel")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        if "_outside/" in filename:
            row.append("Day")
        else:
            row.append("Not Determinable")
        row.append("Weather")
        if "_outside/" in filename:
            row.append("Clear")
        else:
            row.append("Not Determinable")
    elif "ThrowingKnife/Fallout/" in filename:
        row.append("ThrowingKnife")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        if "_inside/" in filename:
            row.append("indoors")
        else:
            row.append("outdoors")
        row.append("What")
        row.append("Knife")
        row.append("On")
        if "_inside/" in filename:
            row.append("NonWoodFloor(inside)")
        else:
            row.append("Gravel")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        if "_outside/" in filename:
            row.append("Day")
        else:
            row.append("Not Determinable")
        row.append("Weather")
        if "_outside/" in filename:
            row.append("Clear")
        else:
            row.append("Not Determinable")
    
    # Skyrim videos
    elif "Archery/Skyrim/" in filename:
        row.append("Archery")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("With")
        row.append("Bow")
        row.append("On")
        row.append("Gravel")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Axe/Skyrim/Axe_whiterun/" in filename:
        row.append("ChoppingWood")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("back")
        row.append("Location")
        row.append("outdoors")
        row.append("With")
        row.append("Axe")
        row.append("On")
        row.append("Grass")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Axe/Skyrim/Axe_Experiment/" in filename:
        label_parts = os.path.basename(filename).lower().split('-')
        row.append("ChoppingWood")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        if label_parts[5] == "b":
            row.append("back")
        elif label_parts[5] == "f":
            row.append("front")
        row.append("Location")
        row.append("outdoors")
        row.append("With")
        row.append("Axe")
        row.append("On")
        row.append("Gravel")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Axe/Skyrim/Axe/" in filename:
        label_parts = os.path.basename(filename).lower().split('-')
        row.append("ChoppingWood")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        if label_parts[4] == "b":
            row.append("back")
        elif label_parts[4] == "l" or label_parts[4] == "r":
            row.append("side")
        elif label_parts[4] == "f":
            row.append("front")
        elif label_parts[4] == "t":
            row.append("top")
        row.append("Location")
        row.append("outdoors")
        row.append("With")
        row.append("Axe")
        row.append("On")
        row.append("Gravel")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        if "n" in label_parts[5]:
            row.append("Night")
        else:
            row.append("Day")
        row.append("Weather")
        if "r" in label_parts[5]:
            row.append("Rain/Fog")
        else:
            row.append("Clear")
    elif "Swimming/Skyrim/Breaststroke/" in filename:
        row.append("Breastroke")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("OpenWater")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Swimming/Skyrim/Underwater/" in filename:
        row.append("Breastroke")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("bottom")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("OpenWater")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Not Determinable")
        row.append("Weather")
        row.append("Not Determinable")
    elif "Swimming/Skyrim/Animals/" in filename:
        label_parts = os.path.basename(filename).lower().split('-')
        row.append("Breastroke")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        if label_parts[2] == "b":
            row.append("back")
        elif label_parts[2] == "l" or label_parts[2] == "r":
            row.append("side")
        elif label_parts[2] == "f":
            row.append("front")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("OpenWater")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
        row.append("Agent")
        if "bear" in label_parts[1]:
            row.append("Bear")
        elif "horse" in label_parts[1]:
            row.append("Horse")
        elif "dog" in label_parts[1] or "husky" in label_parts[1] or \
                "fox" in label_parts[1] or "wolf" in label_parts[1]:
            row.append("Dog")
        else:
            row.append("Other")
    elif "Hammering/Skyrim/" in filename:
        row.append("Hammering")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        if os.path.basename(filename)[-9] == 'c':
            row.append("front")
        else:
            row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("With")
        row.append("Hammer")
        row.append("On")
        row.append("Gravel")
        row.append("What")
        row.append("Anvil")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Jumping/Skyrim/" in filename:
        row.append("Jumping")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        if os.path.basename(filename)[-8] == 'm':
            row.append("Grass")
        else:
            row.append("Gravel")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "HorseRiding/Skyrim/" in filename:
        label_parts = os.path.basename(filename).lower().split('-')
        row.append("RidingHorse")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        if label_parts[5] == "b":
            row.append("back")
        elif label_parts[5] == "f":
            row.append("front")
        elif "t" in label_parts[5]:
            row.append("top")
        else:
            row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Gravel")
        row.append("What")
        row.append("Horse")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Running/Skyrim/" in filename:
        row.append("Running")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Gravel")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Sleeping/Skyrim/Sleeping_whiterun/" in filename:
        row.append("Sleeping")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        if os.path.basename(filename)[-5] == 'r':
            row.append("side")
        elif os.path.basename(filename)[-5] == 't':
            row.append("top")
        else:
            row.append("front")
        row.append("Location")
        row.append("indoors")
        row.append("On")
        row.append("WoodFloor")
        row.append("With")
        row.append("Bed")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Sleeping/Skyrim/Sleeping/" in filename:
        label_parts = os.path.basename(filename).lower().split('-')
        row.append("Sleeping")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        if label_parts[5] == "s":
            row.append("side")
        if label_parts[5] == 't':
            row.append("top")
        row.append("Location")
        if label_parts[4] == "s":
            row.append("indoors")
        else:
            row.append("outdoors")
        row.append("On")
        row.append("WoodFloor")
        row.append("With")
        row.append("Bed")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        if label_parts[4] == "s":
            row.append("Not Determinable")
        elif label_parts[4] =="vn":
            row.append("Night")
        else:
            row.append("Day")
        row.append("Weather")
        if label_parts[4] == "s":
            row.append("Not Determinable")
        else:
            row.append("Clear")
    elif "Standing/Skyrim/standing_forest/" in filename:
        row.append("Standing")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("back")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Grass")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Standing/Skyrim/standing_forest_side/" in filename:
        row.append("Standing")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        if os.path.basename(filename)[-8] == 'm':
            row.append("Grass")
        else:
            row.append("Gravel")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Standing/Skyrim/standing_town/" in filename:
        row.append("Standing")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("back")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        if os.path.basename(filename)[-5] == '4':
            row.append("WoodFloor")
        else:
            row.append("Gravel")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Standing/Skyrim/standing_town_side/" in filename:
        row.append("Standing")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        if os.path.basename(filename)[-5] == '4':
            row.append("WoodFloor")
        else:
            row.append("Gravel")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Walking/Skyrim/Walking_stepped/" in filename:
        row.append("Walking")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Gravel")
        row.append("With")
        row.append("None")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Walking/Skyrim/Walking/" in filename:
        label_parts = os.path.basename(filename).lower().split('-')
        row.append("Walking")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        if label_parts[4] == "b":
            row.append("back")
        elif label_parts[4] == "l" or label_parts[4] == "r":
            row.append("side")
        elif label_parts[4] == "f":
            row.append("front")
        elif "t" in label_parts[4]:
            row.append("top")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Gravel")
        row.append("With")
        row.append("None")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        if "n" in label_parts[5]:
            row.append("Night")
        else:
            row.append("Day")
        row.append("Weather")
        if "r" in label_parts[5]:
            row.append("Rain/Fog")
        else:
            row.append("Clear")
    elif "Walking/Skyrim/WalkingThroughSnow/" in filename:
        row.append("WalkingThroughSnow")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Snow")
        row.append("With")
        row.append("None")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")

    # GTA videos
    elif "Biking/GTA/" in filename:
        row.append("Biking")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Pavement")
        row.append("Participants")
        row.append("Single")
        row.append("What")
        row.append("Cycle")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Motorcycle/GTA/" in filename:
        row.append("Motorcycling")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("What")
        row.append("Motorcycle")
        row.append("Participants")
        row.append("Single")
        row.append("On")
        row.append("Pavement")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Running/GTA/" in filename:
        row.append("Running")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("back")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Pavement")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Standing/GTA/StandingCityRear/" in filename or "Standing/GTA/standing_back/" in filename:
        row.append("Standing")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("back")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Pavement")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Standing/GTA/StandingCitySide/" in filename or "Standing/GTA/standing_left/" in filename or "Standing/GTA/standing_right/" in filename:
        row.append("Standing")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Pavement")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Standing/GTA/standing_front/" in filename:
        row.append("Standing")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("front")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Pavement")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Swimming/GTA/" in filename:
        row.append("Swimming")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("OpenWater")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "ThrowingGrenade/GTA/" in filename:
        row.append("ThrowingGrenade")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        if "/throwing_back/" in filename:
            row.append("back")
        elif "/throwing_front/" in filename:
            row.append("front")
        else:
            row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("What")
        row.append("Grenade")
        row.append("On")
        row.append("Pavement")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "JumpingIntoPool/GTA/" in filename:
        row.append("JumpingIntoPool")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        if "/pooljump_front/" in filename:
            row.append("front")
        elif "/pooljump_back/" in filename:
            row.append("back")
        else:
            row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("On")
        row.append("Pool")
        row.append("Participants")
        row.append("Single")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    elif "Jetski/GTA/" in filename:
        row.append("Jetski")
        row.append(f"{filename}")
        row.append("0")
        row.append(f"{get_framecount(filename)}")
        row.append("Perspective")
        if "/jetskiing_back/" in filename:
            row.append("back")
        elif "/jetskiing_front/" in filename:
            row.append("front")
        else:
            row.append("side")
        row.append("Location")
        row.append("outdoors")
        row.append("What")
        row.append("SkiJet")
        row.append("Participants")
        row.append("Single")
        row.append("On")
        row.append("OpenWater")
        row.append("TimeOfDay")
        row.append("Day")
        row.append("Weather")
        row.append("Clear")
    else:
        raise Exception(f"{filename} not tied to a specified category. Please check file directory and/or add new annotation(s)")

    while len(row) < 22:
        row.append("NA")
        row.append("None")
    row.append("0")
    return row

files = glob.glob(f"**/*.mp4", recursive=True)
files = [f.replace('\\', '/') for f in files]
print(f"files found: {len(files)}")

with open(f"sail_on_synthetic_annotations.csv", "w", newline="") as f:
    writer = csv.writer(f)
    for j, vf in enumerate(files):
        r = makerow(vf)
        if len(r) == 0:
            continue
        checkrow(r, j)
        writer.writerow(r)
        if j % 100 == 0:
            print(f"{j}/{len(files)} annotated")
print("Annotation process finished!")